// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
"use strict";

var Intro = require("./intro.js");
var React = require("react");
var Header = require("./header.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Home");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return React.createElement(
      "section",
      undefined,
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        Header.make("ReasonReact example", /* array */ [])
      ),
      ReasonReact.element(
        /* None */ 0,
        /* None */ 0,
        Intro.make(/* array */ [])
      )
    );
  };
  return newrecord;
}

var jsComponent = ReasonReact.wrapReasonForJs(component, function() {
  return make(/* array */ []);
});

exports.component = component;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
