// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
"use strict";

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Intro");

var introText =
  "This is the ReasonReact example for the babel-plugin-bucklescript example!";

function make() {
  var newrecord = component.slice();
  newrecord[/* render */ 9] = function() {
    return React.createElement("p", undefined, introText);
  };
  return newrecord;
}

exports.component = component;
exports.introText = introText;
exports.make = make;
/* component Not a pure module */
